### ISSUE TITLE
Payment amount exceeds the amount outstanding on this document

### ISSUE THREAD

**Issue by christo-mabbs11** [dfinnema/woocommerce-xero-stripe-fees#21]
Thanks for creating this, this is exactly what we're looking for. We're having an issue with syncs though. Once a payment is made we get the error "Payment amount exceeds the amount outstanding on this document", error number 10.

It appears to be an issue with the plugin. I've run the exact same order twice. Once with the plugin enabled and disabled and attached the results.

Any help at all would be very much appreciated!

[xero-2019-05-02-b8a5857ec8b2ea5b520b63c17a707bc4 (1).log](https://github.com/dfinnema/woocommerce-xero-stripe-fees/files/3136471/xero-2019-05-02-b8a5857ec8b2ea5b520b63c17a707bc4.1.log)
[xero-2019-05-02-b8a5857ec8b2ea5b520b63c17a707bc4.log](https://github.com/dfinnema/woocommerce-xero-stripe-fees/files/3136472/xero-2019-05-02-b8a5857ec8b2ea5b520b63c17a707bc4.log)

**Comment by dfinnema** [comment]
@christo-mabbs11 Have pushed out a new version, on the master branch if you can please test if this solves your issue.
